### ISSUE TITLE
Unable to deploy via Gallery template

### ISSUE THREAD

**Issue by pedro948** [scautomation/Azure-Automation-Change-Tracking#1]
Hi, 
I am trying to deploy this Workbook via Gallery template.
The workbook is correctly counting the number of reporting machine but it is impossible to click to any dropdown except of Computer.
I am not sure if I am doing something wrong.
![image](https://user-images.githubusercontent.com/63005745/110486011-8364f180-80ec-11eb-85c0-8df46707cb58.png)

Thank you for your advice or fix the problem.

**Comment by scautomation** [comment]
i think i fixed it, pushed a new version, go ahead and re-import the workbook and let me know.

**Comment by pedro948** [comment]
You are a god. Thank you. Fixed!
